mysite/accounts/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path
from .views import (login_view,
                    get_cookies_view,
                    set_cookies_view,
                    get_session_view,
                    set_session_view,
                    logout_view,
                    MyLogoutView,
                    AboutMeView,
                    RegisterView,
                    FooBarView,
                    UpdateProfileView,
                    UserListView,
                    UserDetailView,
                    HelloView,
                    )

app_name = 'accounts'

urlpatterns = [
    # path('login/', login_view, name='login')
    path('login/',LoginView.as_view(template_name='accounts/login.html', redirect_authenticated_user=True),
        name='login'
    ),
    path('logout/', logout_view, name='logout'),
    # path('logout/', MyLogoutView.as_view(), name='logout'),
    path('cookies/get/', get_cookies_view, name='cookies_get'),
    path('cookies/set/', set_cookies_view, name='cookies_set'),

    path('session/get/', get_session_view, name='session_get'),
    path('session/set/', set_session_view, name='session_set'),


    path("about-me/", AboutMeView.as_view(), name="about-me"),
    path("register/", RegisterView.as_view(), name="register"),
    path('update/', UpdateProfileView.as_view(), name='update_profile'),
    path('users-list/', UserListView.as_view(), name='users_list'),
    path('user-detail/<int:pk>/', UserDetailView.as_view(), name='user_detail'),

    path("foo-bar/", FooBarView.as_view(), name="foo-bar"),

    path("hello/", HelloView.as_view(), name="hello"),
]

mysite/blogapp/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView

from .views import (ArticlesListView,
                    ArticleDetailView,
                    ArticleCreateView,
                    CreateUserView,
                    ArticleUpdateView,
                    ArticleDeleteView,
                    LatestArticlesFeed
                    )

app_name = 'blogapp'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('articles/', ArticlesListView.as_view(), name='articles'),
    path('articles/<int:pk>', ArticleDetailView.as_view(), name='article_details'),
    path('articles/<int:pk>/edit/', ArticleUpdateView.as_view(), name='article_edit'),
    path('article/<int:pk>/delete/', ArticleDeleteView.as_view(), name='article_delete'),

    # pk is the model object's primary key
    path('articles/new/', ArticleCreateView.as_view(), name='article_create'),
    path('articles/latest/feed/', LatestArticlesFeed(), name='articles_feed'),
    path("register/", CreateUserView.as_view(), name="register"),
]

mysite/myauth/urls.py
from django.urls import path, include

from accounts.views import UserListView
from .views import login_view

app_name = 'myauth'


urlpatterns = [
    path('login/', login_view, name='login'),
    ]

mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin, sitemaps
from django.urls import path, include
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView, SpectacularRedocView
from django.contrib.sitemaps.views import sitemap
from .sitemaps import sitemaps_dict

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('auth/', include('accounts.urls')),
    path('shop/', include('shopapp.urls')),
    path('req/', include('requestdataapp.urls')),
    path("api/", include("myapiapp.urls")),
    path('blogapp/', include('blogapp.urls')),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps_dict}, name="django.contrib.sitemaps.views.sitemap"),
]

urlpatterns += i18n_patterns(
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('shop/', include('shopapp.urls')),
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path("api/schema/swagger/", SpectacularSwaggerView.as_view(url_name='schema'), name="swagger"),
    path("api/schema/redoc/", SpectacularRedocView.as_view(url_name='schema'), name="redoc"),
    path("api/", include("myapiapp.urls")),
    path('blogapp/', include('blogapp.urls')),
    path(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps_dict},
         name='django.contrib.sitemaps.views.sitemap'),
)

if settings.DEBUG:
    urlpatterns.extend(static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )
    urlpatterns.extend(static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )
    urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')))

mysite/shopapp/urls.py
from django.urls import path, include

from rest_framework.routers import DefaultRouter

from .views import (
    ShopIndexView,
    GroupsListView,
    ProductsDetailsView,
    ProductsListView,
    OrderDetailView,
    ProductCreateView,
    ProductUpdateView,
    create_order,
    OrdersListView,
    ProductDeleteView,
    OrderUpdateView,
    OrderCreateView,
    OrderDeleteView,
    example_view,
    ProductViewSet, OrderViewSet,
)

app_name = "shopapp"

routers = DefaultRouter()
# routers.register("shops", ShopIndexView, basename="shops")
routers.register("products", ProductViewSet, basename="products")
routers.register("orders", OrderViewSet, basename="orders")

urlpatterns = [
    path("api/", include(routers.urls)),

    path("", (ShopIndexView.as_view()), name="index"),
    path("groups/", GroupsListView.as_view(), name="groups_list"),

    path("products/", ProductsListView.as_view(), name="products_list"),
    path("products/<int:pk>/", ProductsDetailsView.as_view(), name="product_details"),
    path("products/create/", ProductCreateView.as_view(), name="product_create"),
    path("products/<int:pk>/update/", ProductUpdateView.as_view(), name="product_update"),
    path("products/<int:pk>/confirm-archive/", ProductDeleteView.as_view(), name="product_delete"),

    path("orders/", OrdersListView.as_view(), name="orders_list"),
    path("orders/create/", OrderCreateView.as_view(), name="order_create"),
    path("orders/<int:pk>/", OrderDetailView.as_view(), name="order_details"),
    path("orders/<int:pk>/update/", OrderUpdateView.as_view(), name="order_update"),
    path("orders/<int:pk>/confirm-delete/", OrderDeleteView.as_view(), name="order_delete"),

    path('example/', example_view, name='example_url'),
]

mysite/accounts/models.py
from django.contrib.auth.models import User
from django.db import models


def user_directory_path(instance, filename):
    return 'users/user_{0}/{1}'.format(instance.user.id, filename)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    profile_picture = models.ImageField(upload_to=user_directory_path, null=True, blank=True)
    agreement_accepted = models.BooleanField(default=False)

mysite/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('bio', 'profile_picture',)

mysite/accounts/views.py
from random import random

from django.contrib.auth.decorators import login_required, permission_required, user_passes_test
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth.views import LogoutView, LoginView
from django.http import HttpRequest, HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse, reverse_lazy
from django.views import View
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import cache_page

from .models import User
from django.views.generic import TemplateView, CreateView, ListView, DetailView

from .forms import UserForm, ProfileForm

from django.utils.translation import gettext as __, gettext_lazy as _, ngettext


class HelloView(View):
    welcome_message = _('welcome hello world')

    def get(self, request: HttpRequest) -> HttpResponse:
        items_str = request.GET.get('items') or 0
        items = int(items_str)
        products_line = ngettext(
            'one product',
            '{count} products',
            items
        )
        product_line = products_line.format(count=items)
        return HttpResponse(
            f'<h1>{self.welcome_message}</h1>'
            f'<h2>{product_line}</h2>'
        )

def login_view(request: HttpRequest) -> HttpResponse:
    if request.method == 'GET':
        if request.user.is_authenticated:
            return redirect('/admin/')

        return render(request, 'accounts/login.html')

    username = request.POST['username']
    password = request.POST['password']

    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        return redirect('/admin')

    return render(request, 'accounts/login.html', {'error': 'Invalid username or password.'})


def logout_view(request: HttpRequest) -> HttpResponse:
    logout(request)
    return redirect(reverse('accounts:login'))


class MyLogoutView(LogoutView):
    next_page = reverse_lazy('accounts:login')


class UpdateProfileView(LoginRequiredMixin, View):
    template_name = 'accounts/profile_update_form.html'

    def get(self, request: HttpRequest) -> HttpResponse:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)

        context = {
            'user_form': user_form,
            'profile_form': profile_form
        }

        return render(request, self.template_name, context)

    def post(self, request: HttpRequest) -> HttpResponse:
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, request.FILES, instance=request.user.profile)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return redirect('accounts:login')

        context = {
            'user_form': user_form,
            'profile_form': profile_form
        }

        return render(request, self.template_name, context)


@user_passes_test(lambda u: u.is_superuser)
def set_cookies_view(request: HttpRequest) -> HttpResponse:
    response = HttpResponse('Cookie set', content_type='text/plain', charset='utf-8', status=200)
    response.set_cookie('fizz', 'buzz', max_age=3600)
    return response


@cache_page(60 +2)
def get_cookies_view(request: HttpRequest) -> HttpResponse:
    value = request.COOKIES.get('fizz', 'default_value')
    return HttpResponse(f'Cookie value: fizz={value!r} + {random()}')


@permission_required('accounts.view_profile', raise_exception=True)
def set_session_view(request: HttpRequest) -> HttpResponse:
    response = HttpResponse('Session set!', content_type='text/plain', charset='utf-8', status=200)
    request.session['foobar'] = 'spameggs'
    return response


@login_required
def get_session_view(request: HttpRequest) -> HttpResponse:
    value = request.session.get('foobar', 'default_value')
    return HttpResponse(f'Session value: {value!r}', content_type='text', charset='utf-8', status=200)


class AboutMeView(TemplateView):
    template_name = "accounts/about-me.html"


class RegisterView(CreateView):
    model = User  # Link to the model for the User, provided by Django's auth system.
    form_class = UserCreationForm  # UserCreationForm is a form for creating a new user.
    template_name = 'accounts/register.html'

    # This func returns the context to be used in the template.
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)  # Calls the base implementation first to get a context

        # Check if it is a POST request (form submission)
        if self.request.POST:
            # Create profile form with submitted data
            context['profile_form'] = ProfileForm(self.request.POST)
        else:
            # Create a new blank profile form
            context['profile_form'] = ProfileForm()

        # Return context dictionary
        return context

    # Called when the UserCreationForm is submitted and passes validation
    def form_valid(self, form):
        context = self.get_context_data()
        profile_form = context['profile_form']  # Extract profile form from context

        self.object = form.save()  # Save the user form and get the created user instance

        if profile_form.is_valid():  # Check if profile form data is valid

            # Save the profile form without committing to database,
            # so user can be associated first
            profile = profile_form.save(commit=False)
            # Associate the profile form's user with the user form's user instance
            profile.user = self.object
            # Save profile instance, which now includes user relation, to the database
            profile.save()
        else:
            # If form is not valid, re-render the page with form error messages
            return self.render_to_response(self.get_context_data(form=form))

        # Calls super's form_valid to finish things up
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('accounts:login')


class FooBarView(View):
    def get(self, request: HttpRequest) -> JsonResponse:
        return JsonResponse({'message': 'Hello', 'foo': 'bar', 'spam': 'eggs'})


class UserListView(ListView):
    model = User
    template_name = 'accounts/users-list.html'
    context_object_name = 'users'


class UserDetailView(DetailView):
    model = User
    template_name = 'accounts/user-detail.html'
    context_object_name = 'user'

mysite/accounts/templates/accounts/about-me.html
{% extends 'accounts/base.html' %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/main.css' %}">

{% block title %}
  About me
{% endblock %}

{% block body %}
	<div class="fixed-container-login">
		<div class="row">
			  {% if user.is_authenticated %}
					   <h1>{{ user.first_name }} {{ user.last_name }}</h1>

						<!-- Check if user has a profile picture -->
						{% if user.profile.profile_picture %}
		                   <!-- Display user's picture -->
		                        <img src="{{ user.profile.profile_picture.url }}" alt="{{ user.username }}'s profile picture">
						{% else %}
							<p>Profile Photo: <em>The user does not have a photo</em></p>
						{% endif %}
						  <!-- Display user's bio -->
						  <div class="card-title product-details">
							   <h4>Username: <b><em>{{ user.username }}</em></b>
							   </h4>
						  <!-- Display user's email -->
							  {% if user.email %}
							        <p>Email: {{ user.email }}</p>
							  {% else %}
								    <p>Email: <em>This user does not have an email</em></p>
							  {% endif %}
						  <!-- Display user's bio -->
							  {% if user.profile.bio %}
							        <p>Bio: {{ user.profile.bio }}</p>
							  {% else %}
								    <p>Bio: <em>This user does not have a bio</em></p>
							  {% endif %}

				            <div class="back-to-list">
					            <a href="{% url 'accounts:update_profile' %}">Edit account</a>
				            </div>
				{% else %}
					  <p>Please login to see this page</p>
            </div><br>
				{% endif %}
		</div>
		<div>
            <a href="{% url 'accounts:users_list' %}">See all users list</a>
        </div><br>
	</div>

{% endblock %}

mysite/accounts/templates/accounts/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
    <title>
        {% block title %}

	    {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <link rel="stylesheet" href="{% static 'css/create-product.css' %}">
    <link rel="stylesheet" href="{% static 'css/create-order.css' %}">

</head>
<body>
<header>
	<div class="fixed-container">
		<div class="header-links">
			<a href="{% url 'shopapp:index' %}">Home</a>
			<a href="{% url 'shopapp:products_list' %}">Products</a>
			<a href="{% url 'shopapp:orders_list' %}">Orders List</a>
		</div>
		<div class="header-links">
			  {% if user.is_authenticated %}
			        Hallo user
				  <a href="{% url 'accounts:about-me' %}"><b>{{ user.username }}</b></a>
			  {% else %}
					Hallo!</b>
			{% endif %}
		</div>
		<div class="header-links">
			<a href="{% url 'accounts:login' %}">Login</a>
			<a href="{% url 'accounts:register' %}">Registration</a>
			<a href="{% url 'blogapp:articles' %}">Blog</a>
			<a href="{% url 'accounts:about-me' %}">About me</a>
			<a href="{% url 'accounts:logout' %}">Logout</a>
		</div>
	</div>
</header>

<div class="fixed-container">
{% block body %}

{% endblock %}
</div>
{% block footer %}
<footer>
	<br>
    <div class="footer">
        <div class="fixed-container">
            <p> Company © 2024. All rights reserved.</p>
        </div>
    </div>
</footer>
{% endblock %}
</body>
</html>

mysite/accounts/templates/accounts/login.html
{% extends 'accounts/base.html' %}

{% block title %}
	Login
{% endblock %}

{% block body %}
	<div class="fixed-container-login">
	    <h1>Login</h1>
		<form method="post">
		{% csrf_token %}
			{{ form.as_p }}
		<button type="submit">Login</button>
		</form>
	</div>
{% endblock %}

mysite/accounts/templates/accounts/logout.html
{% extends 'accounts/base.html' %}

{% block title %}
    Logout
{% endblock %}

{% block body %}
    <h1>Logout</h1>
    <p>Are you sure you want to logout?</p>
    <form method="post" action="{% url 'accounts:logout' %}">
        {% csrf_token %}
        <button type="submit">Logout</button>
    </form>
{% endblock %}

mysite/accounts/templates/accounts/profile_update_form.html
{% extends 'accounts/base.html' %}

{% block title %}
  Profile Update
{% endblock %}

{% block body %}
	<section>
		<div class="fixed-container-login">
			  {% if user.is_authenticated %}
			    <h1>Profile Update</h1>
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ user_form.as_p }}
                        {{ profile_form.as_p }}
                        <button type="submit">Update</button>
                    </form>
			  {% else %}
			    <h2>User is anonymous</h2>
			  {% endif %}
		</div>
	</section>

{% endblock %}

mysite/accounts/templates/accounts/user-detail.html
{% extends 'accounts/base.html' %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/main.css' %}">

{% block title %}
  User Detail
{% endblock %}

{% block body %}
	<div class="fixed-container">
		<div class="row">
			  {% if user.is_authenticated %}
				  <h2>User Detail</h2>
					   <h2>{{ user.first_name }} {{ user.last_name }}</h2>
						<!-- Check if user has a profile picture -->
						{% if user.profile.profile_picture %}
		                   <!-- Display user's picture -->
		                        <img src="{{ user.profile.profile_picture.url }}" alt="{{ user.username }}'s profile picture">
						{% else %}
							<p>Profile Photo: <em>The user does not have a photo</em></p>
						{% endif %}
						  <!-- Display user's bio -->
						  <div class="card-title product-details">
							   <h4>Username: <b><em>{{ user.username }}</em></b></h4>
						        <!-- Display user's email -->
							  {% if user.email %}
							        <p>Email: {{ user.email }}</p>
							  {% else %}
								    <p>Email: <em>This user does not have an email</em></p>
							  {% endif %}
								<!-- Display user's bio -->
							  {% if user.profile.bio %}
							        <p>Bio: {{ user.profile.bio }}</p>
							  {% else %}
								    <p>Bio: <em>This user does not have a bio</em></p>
							  {% endif %}

				            <div class="back-to-list">
					            <a href="{% url 'accounts:update_profile' %}">Edit account</a>
				            </div>
				{% else %}
					  <p>Please login to see this page</p>
            </div><br>
				{% endif %}
		</div>
		<div>
            <a href="{% url 'accounts:users_list' %}">See all users list</a>
        </div><br>
	</div>

{% endblock %}

mysite/accounts/templates/accounts/users-list.html
{% extends 'accounts/base.html' %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/main.css' %}">

{% block title %}
  About me
{% endblock %}

{% block body %}
	<div class="fixed-container-login">
		<div class="row">
			  {% if user.is_authenticated %}
				  <h1>Users list:</h1>
				  {% if users %}
				  	<ol>
				        {% for user in users %}
				        	<li>
					            Username: <a href="{% url 'accounts:user_detail' user.id %}">{{ user.username }}</a><br>
					            Name: {{ user.first_name }} {{ user.last_name }} <br>
					            Email: {{ user.email }}<br><br>
					        </li>
				        {% endfor %}
				    </ol>
					  {% else %}
					    <p>No users are available</p>
				  {% endif %}

				{% else %}
					  <p>Please login to see this page</p>
            </div><br>
				{% endif %}
		</div>
	</div>

{% endblock %}