mysite/myauth/urls.py
from django.urls import path, include

from accounts.views import UserListView
from .views import login_view

app_name = 'myauth'


urlpatterns = [
    path('login/', login_view, name='login'),
    ]

mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin, sitemaps
from django.urls import path, include
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView, SpectacularRedocView
from django.contrib.sitemaps.views import sitemap
from .sitemaps import sitemaps_dict

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('auth/', include('accounts.urls')),
    path('shop/', include('shopapp.urls')),
    path('req/', include('requestdataapp.urls')),
    path("api/", include("myapiapp.urls")),
    path('blogapp/', include('blogapp.urls')),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps_dict}, name="django.contrib.sitemaps.views.sitemap"),
]

urlpatterns += i18n_patterns(
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('shop/', include('shopapp.urls')),
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path("api/schema/swagger/", SpectacularSwaggerView.as_view(url_name='schema'), name="swagger"),
    path("api/schema/redoc/", SpectacularRedocView.as_view(url_name='schema'), name="redoc"),
    path("api/", include("myapiapp.urls")),
    path('blogapp/', include('blogapp.urls')),
    path(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps_dict},
         name='django.contrib.sitemaps.views.sitemap'),
)

if settings.DEBUG:
    urlpatterns.extend(static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )
    urlpatterns.extend(static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )
    urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')))

mysite/shopapp/urls.py
from django.urls import path, include

from rest_framework.routers import DefaultRouter

from .views import (
    ShopIndexView,
    GroupsListView,
    ProductsDetailsView,
    ProductsListView,
    OrderDetailView,
    ProductCreateView,
    ProductUpdateView,
    create_order,
    OrdersListView,
    ProductDeleteView,
    OrderUpdateView,
    OrderCreateView,
    OrderDeleteView,
    example_view,
    ProductViewSet, OrderViewSet,
)

app_name = "shopapp"

routers = DefaultRouter()
# routers.register("shops", ShopIndexView, basename="shops")
routers.register("products", ProductViewSet, basename="products")
routers.register("orders", OrderViewSet, basename="orders")

urlpatterns = [
    path("api/", include(routers.urls)),

    path("", (ShopIndexView.as_view()), name="index"),
    path("groups/", GroupsListView.as_view(), name="groups_list"),

    path("products/", ProductsListView.as_view(), name="products_list"),
    path("products/<int:pk>/", ProductsDetailsView.as_view(), name="product_details"),
    path("products/create/", ProductCreateView.as_view(), name="product_create"),
    path("products/<int:pk>/update/", ProductUpdateView.as_view(), name="product_update"),
    path("products/<int:pk>/confirm-archive/", ProductDeleteView.as_view(), name="product_delete"),

    path("orders/", OrdersListView.as_view(), name="orders_list"),
    path("orders/create/", OrderCreateView.as_view(), name="order_create"),
    path("orders/<int:pk>/", OrderDetailView.as_view(), name="order_details"),
    path("orders/<int:pk>/update/", OrderUpdateView.as_view(), name="order_update"),
    path("orders/<int:pk>/confirm-delete/", OrderDeleteView.as_view(), name="order_delete"),

    path('example/', example_view, name='example_url'),
]

mysite/shopapp/forms.py
from django.contrib.auth.models import Group
from django.forms import ModelForm, forms

from shopapp.models import Product, Order


class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'price', 'description', 'discount']


class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = ['delivery_address', 'promocode', 'user', 'products']


class GroupForm(ModelForm):
    class Meta:
        model = Group
        fields = ['name']


class CSVImportForm(forms.Form):
    csv_file = forms.FileField(label='CSV File')

mysite/shopapp/views.py
import csv
import logging
from timeit import default_timer

from attr import field
from django.contrib.auth.mixins import (LoginRequiredMixin,
                                        PermissionRequiredMixin,
                                        UserPassesTestMixin)
from django.contrib.auth.models import Group
from django.http import (HttpResponse,
                         HttpRequest,
                         HttpResponseRedirect,
                         HttpResponseForbidden)
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from django.views.generic import (TemplateView,
                                  ListView,
                                  DetailView,
                                  CreateView,
                                  UpdateView,
                                  DeleteView)
from django.views import View
from rest_framework.decorators import action

from rest_framework.generics import ListCreateAPIView
from rest_framework.parsers import MultiPartParser
from rest_framework.response import Response
from rest_framework.viewsets import ModelViewSet
from rest_framework.filters import SearchFilter, OrderingFilter
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework import generics, decorators, permissions, status, viewsets
from rest_framework.request import Request
from drf_spectacular.utils import extend_schema, OpenApiResponse

from .serializers import ProductSerializer, OrderSerializer

from .forms import ProductForm, OrderForm, GroupForm
from .models import Product, Order

from .common import save_csv_products

log = logging.getLogger(__name__)



class ShopIndexView(View):
    """
    A class-based view for rendering the shop index page.

    Methods:
    - get(request: HttpRequest) -> HttpResponse: Renders the shop index page.

    """
    @method_decorator(cache_page(60 * 2))
    def get(self, request: HttpRequest) -> HttpResponse:
        products = [
            ('Laptop', 1999),
            ('Desktop', 2999),
            ('Smartphone', 999),
        ]
        context = {
            "time_running": default_timer(),
            "products": products,
            "items": len(Product.objects.all())
        }
        log.debug('Products for shop index: %s', products)
        log.info("Rendering shop index page")

        print('shop index context', context)
        return render(request, 'shopapp/shop-index.html', context=context)


class GroupsListView(View):
    """
    GroupsListView

    A class-based view for displaying a list of groups.

    Methods:
        - get(request: HttpRequest) -> HttpResponse
        - post(request: HttpRequest) -> HttpResponse

    Attributes:
        - None

    Methods:
        - get(request: HttpRequest) -> HttpResponse:
            Displays the groups list page with a form and a list of groups.

            Parameters:
                - request (HttpRequest): The HTTP request object.

            Returns:
                - HttpResponse: The rendered HTTP response with the groups list page.

        - post(request: HttpRequest) -> HttpResponse:
            Handles the submission of the group form.

            Parameters:
                - request (HttpRequest): The HTTP request object.

            Returns:
                - HttpResponse: The redirect response to the current URL.

    Example usage:
    ```python
    # Create an instance of the GroupsListView
    groups_list_view = GroupsListView()

    # Call the get() method
    response = groups_list_view.get(request)

    # Call the post() method
    response = groups_list_view.post(request)
    ```
    """

    def get(self, request: HttpRequest) -> HttpResponse:
        context = {
            "form": GroupForm(),
            "groups": Group.objects.prefetch_related('permissions').all(),
        }
        return render(request, 'shopapp/groups-list.html', context=context)

    def post(self, request: HttpRequest) -> HttpResponse:
        form = GroupForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect(request.path)


class ProductsDetailsView(DetailView):
    """
    The ProductsDetailsView class is a subclass of the DetailView class in Django.
    It is used to retrieve and display details of a specific Product object from the database.

    Attributes:
        - template_name (str): The name of the HTML template file to be used for rendering the view.
        - model (Model): The model class representing the Product object.
        - context_object_name (str): The name of the variable that will be used
          to access the Product object in the template.

    Methods:
        - get(self, request: HttpRequest, pk: int) -> HttpResponse:
            Retrieves the Product object with the given primary key (pk) from the database and renders
            the template with the retrieved object as the context.

            Parameters:
                - request (HttpRequest): The request object received from the client.
                - pk (int): The primary key of the Product object to be retrieved.

            Returns:
                - HttpResponse: The rendered HTML response containing the product details.

    """
    template_name = 'shopapp/product-details.html'
    model = Product
    context_object_name = "product"

    # def get(self, request: HttpRequest, pk: int) -> HttpResponse:
    # product = get_object_or_404(Product, pk=pk)
    # context = {
    #     "product": product
    # }
    # return render(request, 'shopapp/product-details.html', context=context)


class ProductsListView(ListView):
    """

    :class: ProductsListView

    A class that displays a list of products.

    Attributes:
    ----------
    - ``template_name``: (`str`) The template name for rendering the products list.
        Default is 'shopapp/products-list.html'.
    - ``context_object_name``: (`str`) The name of the variable to be used in the template for the list of products.
        Default is 'products'.
    - ``queryset``: (`QuerySet`) The queryset of products to be used for displaying the list. By default, it filters
        Product objects where archived=False.

    """
    template_name = 'shopapp/products-list.html'
    # def get_context_data(self, **kwargs):
    # context = super().get_context_data(**kwargs)
    # context['products'] = Product.objects.all()
    # return context
    # model = Product
    context_object_name = 'products'
    queryset = Product.objects.filter(archived=False)


class ProductCreateView(CreateView):
    """

    :class: ProductCreateView

    A class-based view for creating a new product in the shop application.

    Attributes:
        - model: The model class that the view is associated with (Product)
        - fields: The fields of the model that should be included in
                the form (name, price, description, discount, preview)
        - success_url: The URL to redirect to after successfully
                creating the product (reverse_lazy('shopapp:products_list'))

    Methods:
        - test_func(): Checks if the user is a superuser or has the permission to create a product.
          Returns True if the user is authorized, False otherwise.
        - form_valid(form): Overrides the form_valid method of CreateView. Sets the 'created_by' attribute of
          the form instance to the current user and calls the base implementation of form_valid.

    """

    def test_func(self):
        return self.request.user.is_superuser or self.request.user.has_perm('shopapp.can_create_product')

    model = Product
    fields = ['name', 'price', 'description', 'discount', 'preview']
    success_url = reverse_lazy('shopapp:products_list')

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)


class ProductUpdateView(UpdateView):
    """
    ProductUpdateView class is a view that allows users to update a product. It inherits from Django's UpdateView class.

    Attributes:
        - model (class attribute): The model class that the view will be based on.
          In this case, it is the Product model.
        - fields (class attribute): The fields of the model that will be editable in the update form.
        - template_name_suffix (class attribute): The suffix to append to the template name for
          rendering the update form.

    Methods:
        - test_func(): Checks if the user has permission to edit this product. Returns True if the user is a superuser
          or if they have the 'shopapp.change_product' permission and they are the author of the product.
          Returns False otherwise.
        - dispatch(request, *args, **kwargs): Overrides the dispatch method of the parent class.
          If the user does not have permission to edit this product, it returns an HttpResponseForbidden with an
          error message. Otherwise, it calls the dispatch method of the parent class.
        - get_success_url(): Returns the URL to redirect to after a successful update. The URL is generated using
          the 'shopapp:product_details' URL pattern and includes the primary key of the updated object.
    """
    model = Product
    fields = ['name', 'price', 'description', 'discount', 'preview']
    template_name_suffix = '_update_form'

    def test_func(self):
        # Check if the user is a superuser
        if self.request.user.is_superuser:
            return True
        # Check if the user has permission to edit
        elif self.request.user.has_perm('shopapp.change_product'):
            # Check if the user is the author of the product
            product = self.get_object()
            return product.created_by == self.request.user
        return False

    def dispatch(self, request, *args, **kwargs):
        if not self.test_func():

mysite/shopapp/templates/shopapp/base.html
<style>
	 * {
		 font-family: 'Roboto', sans-serif;
	}
</style>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
	<link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">
  <title>
    {% block title %}
      Base Title
    {% endblock %}
  </title>

  <style>
	{% block style %}
		/* products-list*/
		.products-list h3 {
			margin: 0;
			font-size: 20px;
			color: #3d52fe;
			text-decoration: underline;
		}

		a {
			color: orangered;
			text-decoration: none;
		}
		a:hover{
			color: green;
			text-decoration: underline;
		}
		* {
            font-family: 'Roboto', sans-serif;
            }
		body{
			text-align: start;
		}

      h1 {
        color: #121212;
      }
    {% endblock %}
  </style>
</head>
<body>

{% block body %}
  Base body
{% endblock %}

</body>
</html>

mysite/shopapp/templates/shopapp/create-order.html
{% extends 'accounts/base.html' %}

{% block title %}
	Create order
{% endblock %}

{% block body %}
	<h1>Create a new order</h1>
    <div>
        <form method="post">
            {% csrf_token %}

            {{ form.as_p }}

            <button type="submit">Create</button>
        </form>
    </div>

     <div>
        <a href="{% url "shopapp:orders_list" %}">Back to orders list
        </a>
    </div>

{% endblock %}

mysite/shopapp/templates/shopapp/create-product.html
{% extends 'accounts/base.html' %}

{% block title %}
	Create product
{% endblock %}

<section>
    {% block body %}
        <div class="fixed-container-login">
            <h1>Create a new product</h1>
            <div>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit">Create</button>
                </form>
            </div>
             <div>
                <a href="{% url "shopapp:products_list" %}">Back to products list
                </a>
            </div>
        </div>
{% endblock %}
</section>

mysite/shopapp/templates/shopapp/groups-list.html
{% extends 'accounts/base.html' %}

{% block title %}
  Groups List
{% endblock %}

{% block body %}
  <h1>Groups:</h1>
	<div>
		<form method="post" >
			{% csrf_token %}
			{{ form.as_p }}
			<button type="submit">Create</button>
		</form>
	</div>
  <div>
  {% if not groups %}
    <h3>No groups yet</h3>
  {% else %}
    <ul>

      {% for group in groups %}
          <li>
            <div>{{ group.name }}</div>
            <ul>
              {% for permission in group.permissions.all %}
                <li>
                  {{ permission.name }}
                  (<code>{{ permission.codename }}</code>)
                </li>
              {% endfor %}

            </ul>
          </li>
      {% endfor %}

    </ul>
  {% endif %}
  </div>
{% endblock %}

mysite/shopapp/templates/shopapp/order_confirm_delete.html
{% extends 'accounts/base.html' %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/main.css' %}">

{% block title %}
	Confirm delete {{ object.name }}
{% endblock %}

{% block body %}
    <div class="fixed-container-login">
        <h1>Are you sure you want to delete  Order #{{ object.pk }}?</h1>
        <br>
        <div class="btn-cancel">
            <a href="{% url 'shopapp:orders_list'%}">Cancel and Back to order list</a>
        </div>
        <div>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="btn-delete">
                    <button type="submit">Delete</button>
                </div>
            </form>
        </div>
    </div>

{% endblock %}

mysite/shopapp/templates/shopapp/order_details_###.html
{% extends 'accounts/base.html' %}

{% block titel %}
	Oder #{{ product.pk }} details
{% endblock %}

{% block body %}
	Oder #{{ product.pk }} details
	 <div>
		 <b>Order by {% firstof object.user.first_name object.user.username %}</b
		 <p>Promocode: <code>{{ object.promocode }}</code></p>
		 <p>Delivery address: {{ object.delivery_address }}</p>
		 <div>
            Product in order:
            <ul>
              {% for product in object.products.all %}
                <li>{{ product.name }} for ${{ product.price }}</li>
              {% endfor %}
            </ul>
		 </div>
	 <div>
	 </div>
		 <a href="{% url 'shopapp/orders_list' %}">Back to orders</a>
	 </div>
{% endblock %}

mysite/shopapp/templates/shopapp/order_list.html
{% extends 'accounts/base.html' %}
{% load static %}

{% block title %}
  Orders list
{% endblock %}

{% block body %}

	<div class="container">
	  <h1>Orders:</h1>
		<div class="row">
		  {% if orders %}
		    <div>
		      {% for order in object_list %}
		        <div>
		          <div class="product-details">
			        <img src="{% static 'img/products/checkout.png' %} " alt="Order Image" class="product-image">
			        <br><br><br>
		          </div>
		            <div class="product-details">
			            <a href="{% url 'shopapp:order_details' pk=order.pk %}" >Details #{{ order.pk }}</a>
		                 <b style="color: mediumblue">Order by {% firstof order.user.first_name order.user.username %}</b>
		                 <p>Promocode: <code>{{ order.promocode }}</code></p>
		                 <p>Delivery address: {{ order.delivery_address }}</p>
		            </div>
		        </div>
		      {% endfor %}
		    </div>
		  {% else %}
		    <h3>No orders yet</h3>
		  {% endif %}
		     <div class="btn-create-new">
		        <a href="{% url "shopapp:order_create" %}">Create a new order</a>
		    </div>
		</div>
	</div>
{% endblock %}

mysite/shopapp/templates/shopapp/order_update_form.html
{% extends 'accounts/base.html' %}

{% block title %}
    Change and update order # {{ object.pk }}
{% endblock %}

{% block body %}
    <h1> Change and update this order #{{ object.pk }}</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Update order</button>
        </form>
    </div>
    <div>
        <a href="{% url 'shopapp:order_details' pk=object.pk %}">Back to order # {{ object.pk }}</a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/product-details.html
{% extends 'accounts/base.html' %}
{% load static %}
{% load i18n %} <!-- Load internationalization tags -->
<link rel="stylesheet" href="{% static 'css/main.css' %}">

{% block title %}
		{% translate 'Product'%}: #{{ product.pk }}
{% endblock %}

{% block body %}
    <div class="container">
        <h1><strong>{% trans product.name %}</strong></h1>
        <div class="row">
            {% if product.preview %}
	         <div class="product-details">
					{% trans 'There is a preview image available for this product' %}
	         </div><br>
                <img src="{{ product.preview.url }}"  alt="{{ product.preview.name }}" class="product-image">
            {% endif %}<br>
            <div class="product-details">
                 <h4 class="card-title product-title">
                     {% trans 'Description' %}: <em>{{ product.description }}</em>
                 </h4>
            </div><br>
            <div class="product-details">
                <h4 class="card-title product-title">
	                {% trans 'Price' %}:<em> {{ product.price }}</em>
                </h4>
            </div><br>
            <div class="product-details ">
                     <h4 class="card-title product-title" > Discount: <em>{{ product.discount }}%</em></h4>
            </div><br>
            <div class="product-details">
	            <h4 class="card-title product-title">
		            {% trans 'Archived'  %}: <em> {{ product.archived }}</em>
	            </h4>
            </div><br>

        </div>
        <div>
	        {% if perms.shopapp.can_create_product %}
			    {% url 'shopapp:product_create' as create_product_url %}
			    {% url 'shopapp:product_update' pk=product.pk as update_product_url %}
			    {% url 'shopapp:product_delete' pk=product.pk as delete_product_url %}
			        {% blocktranslate %}
			            <div class="back-to-list">
			                  <a href="{{create_product_url}}" >Create a New One</a>
			            </div>

			            <div class="back-to-list">
			                  <a href="{{update_product_url}}" >Update product</a>
			            </div>
			            <div class="back-to-list">
			                 <a href="{{delete_product_url}}">Archive product</a>
			            </div>
			        {% endblocktranslate %}
	        {% endif %}
         </div>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/product_confirm_delete.html
{% extends 'accounts/base.html' %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/main.css' %}">

{% block title %}
	Confirm archive {{ object.name }}
{% endblock %}

{% block body %}
	<h1>Are you sure you want archive {{ object.name }}?</h1>
	<br>
	<div>
		<a href="{% url 'shopapp:product_details' pk=object.pk %}">Cancel and Back to product</a>
	</div>
	<br>
	<div>
		<form method="post">
			{% csrf_token %}
			{{ form.as_p }}
            <div class="back-to-list">
			    <button type="submit">Archive</button>
            </div>
		</form>
	</div>
{% endblock %}

mysite/shopapp/templates/shopapp/product_form.html
{% extends 'accounts/base.html' %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/main.css' %}">

{% block title %}
	Create product
{% endblock %}

<section>
    {% block body %}
        <div class="fixed-container-login">
            <h1>Create a new product</h1>
            <div>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit">Create</button>
                </form>
            </div>
             <div class="back-to-list">
                <a href="{% url "shopapp:products_list" %}">Back to products list
                </a>
            </div>
        </div>
{% endblock %}
</section>

mysite/shopapp/templates/shopapp/products-list.html
{% extends 'accounts/base.html' %}
{% load i18n %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/main.css' %}">


{% block title %}
	{% translate 'Products List' %}
{% endblock %}

{% block extra_css %}

{% endblock %}

{% block body %}
  <div class="container">
    <h1 class="">{% translate 'Products'%}</h1>
        <div>
          {% if products %}
	        <div>
		         {% blocktranslate count products_count=products|length%}
		            <h3>There is only one product:</h3>
		        {% plural %}
		            <h3>There are {{ products_count }} products:</h3>
		        {% endblocktranslate %}
	        </div>
            {% for product in products %}
              <div>
                  <div>
                    {% if product.preview %}
                        <img src="{{ product.preview.url }}"  alt="{{ product.preview.name }}" class="product-image">
                    {% endif %}
                      <!--<img src="{% static 'img/products/desktop.png' %}" alt="Product Image" class="product-image"> -->
                  <div class="product-details">
                        <h5 class="card-title product-title">
                          <a href="{% url 'shopapp:product_details' pk=product.pk %}" class="text-dark">{{ product.name }}</a>
                        </h5>
                        <p>{% translate 'Price'%}: ${{ product.price }}</p>
	                    {% translate 'Products'%}
                        <p>{% translate 'Discount'%}: {% if product.discount %}${{ product.discount }}{% else %} {% translate 'No Discount'%}{% endif %}</p>
                  </div>
                  </div>
              </div>
            {% endfor %}

	        {% if perms.shopapp.can_create_product %}
	          <div class="back-to-list">
	            <a href="{% url 'shopapp:product_create' %}" > {% trans "Create a New Product"%}</a>
	          </div>
            {% endif %}

          {% else %}
            <div>
                <div>
	                {% if perms.shopapp.can_create_product %}
	                    {% url 'shopapp:product_create' as create_product_url%}
	                        {% blocktranslate %}
	                            <h3>No products found</h3>
	                            <div class="back-to-list">
	                                <a href="{{create_product_url}}"> Create a New One</a>
	                            </div>
	                        {% endblocktranslate %}
	                {% endif %}
                </div>
            </div>
          {% endif %}
        </div>


  </div>
{% endblock %}

mysite/shopapp/templates/shopapp/products_changelist.html
{% extends 'admin/change_list.html' %}

{% block object-tools-items %}
	{% load admin_urls %}
	<li>
		<a href="{% url 'admin:import_products_csv' %}" class="addlink">Import CSV</a>
	</li>
	{{ block.super }}
{% endblock %}

mysite/shopapp/templates/shopapp/shop-index.html
{% extends 'accounts/base.html' %}

{% block title %}
  Shop Index
{% endblock %}


{% block body %}
  <h1>Hello Shop Index!</h1>

  <div>
    <ul>
      {% for name, price in products %}
        <li>{{ name }} ({{ name|length }}) for ${{ price }}</li>
        {% if name|length_is:'7' %}
          <span>Lucky product!</span>
        {% endif %}
      {% empty %}
        No products here
      {% endfor %}
    </ul>
  </div>

<div>
	<strong>
		You have {{ items }} cherr{{ items|pluralize:"y,es" }}
	</strong>
</div>

  <div>
    Time running: {{ time_running }}
  </div>

  <div>
    {% lorem 3 p random %}
  </div>

{% endblock %}