mysite/blogapp/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView

from .views import (ArticlesListView,
                    ArticleDetailView,
                    ArticleCreateView,
                    CreateUserView,
                    ArticleUpdateView,
                    ArticleDeleteView,
                    LatestArticlesFeed
                    )

app_name = 'blogapp'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('articles/', ArticlesListView.as_view(), name='articles'),
    path('articles/<int:pk>', ArticleDetailView.as_view(), name='article_details'),
    path('articles/<int:pk>/edit/', ArticleUpdateView.as_view(), name='article_edit'),
    path('article/<int:pk>/delete/', ArticleDeleteView.as_view(), name='article_delete'),

    # pk is the model object's primary key
    path('articles/new/', ArticleCreateView.as_view(), name='article_create'),
    path('articles/latest/feed/', LatestArticlesFeed(), name='articles_feed'),
    path("register/", CreateUserView.as_view(), name="register"),
]

mysite/myauth/urls.py
from django.urls import path, include

from accounts.views import UserListView
from .views import login_view

app_name = 'myauth'


urlpatterns = [
    path('login/', login_view, name='login'),
    ]

mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin, sitemaps
from django.urls import path, include
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView, SpectacularRedocView
from django.contrib.sitemaps.views import sitemap
from .sitemaps import sitemaps_dict

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('auth/', include('accounts.urls')),
    path('shop/', include('shopapp.urls')),
    path('req/', include('requestdataapp.urls')),
    path("api/", include("myapiapp.urls")),
    path('blogapp/', include('blogapp.urls')),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps_dict}, name="django.contrib.sitemaps.views.sitemap"),
]

urlpatterns += i18n_patterns(
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('shop/', include('shopapp.urls')),
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path("api/schema/swagger/", SpectacularSwaggerView.as_view(url_name='schema'), name="swagger"),
    path("api/schema/redoc/", SpectacularRedocView.as_view(url_name='schema'), name="redoc"),
    path("api/", include("myapiapp.urls")),
    path('blogapp/', include('blogapp.urls')),
    path(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps_dict},
         name='django.contrib.sitemaps.views.sitemap'),
)

if settings.DEBUG:
    urlpatterns.extend(static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )
    urlpatterns.extend(static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )
    urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')))

mysite/blogapp/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField()

    def __str__(self):
        return self.user.username


class Category(models.Model):
    name = models.CharField(max_length=60)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=60)

    def __str__(self):
        return self.name


class Article(models.Model):
    title = models.CharField(_("Title"), max_length=200)
    content = models.TextField(_("Content"))
    pub_date = models.DateTimeField(_("Publication Date"), null=True, blank=True)
    last_modified = models.DateTimeField(_("Last Modified"), auto_now=True)
    author = models.ForeignKey('Author', verbose_name=_("Author"), on_delete=models.CASCADE)
    category = models.ForeignKey('Category', verbose_name=_("Category"), on_delete=models.CASCADE)
    tags = models.ManyToManyField('Tag', verbose_name=_("Tags"), blank=True)

    def get_absolute_url(self):
        return reverse('blogapp:article_details', kwargs={'pk': self.pk})

    class Meta:
        verbose_name = _("Article")
        verbose_name_plural = _("Articles")
        ordering = ['-pub_date']

    def __str__(self):
        return self.title

mysite/blogapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Author, Article


class AuthorCreateForm(UserCreationForm):
    bio = forms.CharField(max_length=500)

    class Meta:
        model = User
        fields = ["username", "password1", "password2", "bio"]


class ArticleForm(forms.ModelForm):
    author = forms.ModelChoiceField(queryset=Author.objects.all())

    class Meta:
        model = Article
        fields = ['title', 'content', 'author', 'category', 'tags']

mysite/blogapp/views.py
from django.contrib.auth import get_user_model
from django.contrib.syndication.views import Feed
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from .models import Article, Author
from django.urls import reverse_lazy, reverse
from .forms import AuthorCreateForm, ArticleForm


class ArticlesListView(ListView):
    model = Article
    template_name = 'blogapp/article_list.html'
    context_object_name = 'articles'
    queryset = (Article.objects.select_related('author', 'category')
                .prefetch_related('tags').defer('content').filter(pub_date__isnull=False))


class ArticleCreateView(CreateView):
    model = Article
    fields = ['title', 'content', 'pub_date', 'author', 'category', 'tags']
    template_name = 'blogapp/create_article.html'


class ArticleDetailView(DetailView):
    model = Article
    template_name = 'blogapp/article_details.html'


class ArticleUpdateView(UpdateView):
    model = Article
    form_class = ArticleForm
    template_name = 'blogapp/article_update_form.html'
    success_url = reverse_lazy('blogapp:articles')


class ArticleDeleteView(DeleteView):
    model = Article
    template_name = 'blogapp/article_delete_confirm.html'
    success_url = reverse_lazy('blogapp:articles')


# Get the User model
User = get_user_model()


class CreateUserView(CreateView):
    template_name = 'blogapp/register.html'
    form_class = AuthorCreateForm
    success_url = reverse_lazy('accounts:login')

    def form_valid(self, form):
        # the form_valid function is called when a form is deemed to be valid,
        # i.e all form fields have passed validation.
        # Here, we are overriding the form_valid function to perform additional actions.
        # After saving the form data to create the user, we are storing user's bio and creating an Author instance
        # associated with the user.
        user = form.save()
        bio = form.cleaned_data.get('bio')
        Author.objects.create(user=user, bio=bio)
        return super().form_valid(form)


class LatestArticlesFeed(Feed):
    title = "Latest Articles"
    link = "blogapp:articles"
    description = "Updates on the latest articles"

    def items(self):
        return Article.objects.filter(pub_date__isnull=False).order_by('-pub_date')[:5]

    def item_title(self, item: Article):
        return item.title

    def item_description(self, item: Article):
        return item.content[:200]

    def item_link(self, item):
        return reverse('blogapp:article_details', args=[item.pk])

mysite/blogapp/templates/blogapp/article_delete_confirm.html
{% extends 'accounts/base.html' %}

{% block title %}
    Delete Article
{% endblock %}

{% block body %}
	<div class="fixed-container-login">
	    <h2>Are you sure you want to delete this article?</h2>
	    <form method="POST">
	        {% csrf_token %}
		    <div class="btn-delete">
			    <button type="submit">Delete</button>
		    </div>
		    <div class="back-to-list">
			    <a href="{{ object.get_absolute_url }}">No, take me back</a>
		    </div>
	    </form>
	</div>
{% endblock %}

mysite/blogapp/templates/blogapp/article_details.html
{% extends 'accounts/base.html' %}
{% load static %}
{% load i18n %} <!-- Load internationalization tags -->
<link rel="stylesheet" href="{% static 'css/main.css' %}">

{% block title %}
    Article {{ object.title }} Details
{% endblock %}

{% block extra_css %}
{% endblock %}

{% block body %}
  <div class="fixed-container-login">
	    <h1 class="">Article Details</h1>
	    <h2>{{ object.title }}</h2>
	    <p>Publication date: {{ object.pub_date }}</p>
	    <p>Author: <b>{% firstof article.author.user user.username %}</b></p>
	    <p>Category: <b>{{ object.category.name }}</b></p>
	    <p>Tags:
	        {% for tag in object.tags.all %}
	            {{ tag.name }}
	        {% endfor %}
	    </p>
	    <p><b>Content:</b> <br><br>
		    {{ object.content }}</p>
		 <div>
	        {% if perms.shopapp.can_create_product %}
			    {% url 'blogapp:article_create' as create_article_url %}
			    {% url 'blogapp:article_edit' pk=article.pk as edit_article_url %}
			    {% url 'blogapp:article_delete' pk=article.pk as delete_article_url %}
			        {% blocktranslate %}
			            <div class="back-to-list">
			                  <a href="{{create_article_url}}" >Create a New One</a>
			            </div>
			            <div class="back-to-list">
			                  <a href="{{edit_article_url}}" >Update article</a>
			            </div>
			            <div class="back-to-list">
			                 <a href="{{delete_article_url}}">Delete article</a>
			            </div>
			        {% endblocktranslate %}
	        {% endif %}
         </div>
  </div>
{% endblock %}

mysite/blogapp/templates/blogapp/article_list.html
{% extends 'accounts/base.html' %}
{% load i18n %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/main.css' %}">


{% block title %}
	{% translate 'Articles' %}
{% endblock %}

{% block extra_css %}

{% endblock %}

{% block body %}
  <div class="container">
    <h1 class="">{% translate 'Articles'%}</h1>
        <div>
          {% if articles %}
	        <div>
		         {% blocktranslate count articles_count=articles|length%}
		            <h3>There is only one article:</h3>
		        {% plural %}
		            <h3>There are {{ articles_count }} articles:</h3>
		        {% endblocktranslate %}
	        </div>
            {% for article in articles %}
              <div>
                  <div>
						<div class="product-details">
							<h2 class="card-title product-title">
								<a href="{% url 'blogapp:article_details' pk=article.pk %}" class="text-dark">{{ article.title }}</a>
							</h2>
						</div>
	                   <p>{% translate 'Publication date:'%} <b>{{ article.pub_date }}</b></p>
	                   <p>{% translate 'Author:'%} <b>{% firstof article.author.user user.username %}</b></p>
	                   <p>{% translate 'Category:'%} <b>{{ article.category.name }}</b></p>
	                  <p>Tags:
						    {% for tag in article.tags.all %}
						      {{ tag.name }}
						    {% endfor %}
	                  </p>
	                  <br>
                  </div>
              </div>
            {% endfor %}

	        {% if perms.shopapp.can_create_product %}
	          <div class="back-to-list">
	            <a href="{% url 'blogapp:article_create' %}" > {% trans "Create a New Article"%}</a>
	          </div>
            {% endif %}

          {% else %}
            <div>
                <div>
	                {% if perms.shopapp.can_create_product %}
	                    {% url 'blogapp:article_create' as create_article_url%}
	                        {% blocktranslate %}
	                            <h3>No articles found</h3>
	                            <div class="back-to-list">
	                                <a href="{{create_article_url}}"> Create a New One</a>
	                            </div>
	                        {% endblocktranslate %}
	                {% endif %}
                </div>
            </div>
          {% endif %}
        </div>


  </div>
{% endblock %}

mysite/blogapp/templates/blogapp/article_update_form.html
{% extends 'accounts/base.html' %}

{% block title %}
   Update Article
{% endblock %}

{% block body %}
	<div class="fixed-container-login">
	   <h2>Update Article</h2>
	   <form method="post">
	      {% csrf_token %}
	      {{ form.as_p }}
	      <button type="submit">Save changes</button>
	   </form>
	</div>
{% endblock %}

mysite/blogapp/templates/blogapp/create_article.html
{% extends 'accounts/base.html' %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/main.css' %}">

{% block body %}
  <div class="fixed-container-login">
    <h1 class="">Create Article</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
  </div>
{% endblock %}

mysite/blogapp/templates/blogapp/register.html
{% extends 'accounts/base.html' %}

{% block title %}
  Create Account
{% endblock %}

{% block body %}
	<section>
		<div class="fixed-container-login">
	         <h1>Create Account</h1>
				<form method="post">
					{% csrf_token %}
					{{ form.as_p }}
					<input type="submit" value="Create Account">
				</form>
		</div>
	</section>

{% endblock %}